diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.longpaths=true
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=niiikkid@gmail.com
user.name=freelancer
credential.https://git.good-production.xyz.provider=generic
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://git.good-production.xyz/Good-Production/template-for-verstka.git
remote.origin.fetch=+refs/heads/project_cosmopet:refs/remotes/origin/project_cosmopet
branch.project_cosmopet.remote=origin
branch.project_cosmopet.merge=refs/heads/project_cosmopet
user.name=freelancer
